# Generated by Django 2.2.13 on 2021-04-17 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('designation', models.CharField(blank=True, max_length=64)),
                ('department', models.CharField(max_length=128)),
                ('college', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True)),
                ('imagePath', models.ImageField(blank=True, null=True, upload_to='people_pic')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2021)),
                ('heading', models.CharField(max_length=512)),
                ('linkPath', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('heading', models.CharField(max_length=64)),
                ('imagePath', models.ImageField(blank=True, null=True, upload_to='research_media')),
                ('desc', models.TextField(blank=True)),
                ('linkName', models.CharField(blank=True, max_length=64)),
                ('externalLink', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('designation', models.CharField(choices=[('Advisor', 'Advisor'), ('Member', 'Member')], default='Member', max_length=64)),
                ('research_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Research')),
            ],
        ),
    ]
